[package]
name = "rust-build"
version = "0.1.0"
authors = ["Mark Koester <mark.koester1@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"